# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build mai-appanysite-api`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t mai-appanysite-api`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system mai-appanysite-api && \
          adduser --system -G mai-appanysite-api mai-appanysite-api

COPY dist/mai-appanysite-api mai-appanysite-api/
RUN chown -R mai-appanysite-api:mai-appanysite-api .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix mai-appanysite-api --omit=dev -f install

CMD [ "node", "mai-appanysite-api" ]
